name: GitHub Metrics

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          username: muddasirhayat
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          config_timezone: Asia/Karachi

      - name: Upload metrics
        uses: actions/upload-artifact@v3
        with:
          name: github-metrics
          path: github-metrics.svg
